### ISSUE TITLE
expected class-name before ‘{’ token    29 | {

### ISSUE THREAD

**Issue by diloabininyeri** [CopernicaMarketingSoftware/PHP-CPP#460] opened 2020-11-16 10:03 UTC
In file included from /usr/include/phpcpp.h:38,
                 from main.cpp:1:
/usr/include/phpcpp/throwable.h:29:1: error: expected class-name before ‘{’ token
   29 | {
      | ^
/usr/include/phpcpp/throwable.h: In constructor ‘Php::Throwable::Throwable(const string&)’:
/usr/include/phpcpp/throwable.h:43:63: error: expected class-name before ‘(’ token
   43 |     Throwable(const std::string &message) : std::runtime_error(message) {}
      |                                                               ^
/usr/include/phpcpp/throwable.h:43:63: error: expected ‘{’ before ‘(’ token
main.cpp: In function ‘void* get_module()’:
main.cpp:29:43: warning: ‘Php::Namespace& Php::Namespace::add(const char*, void (* const&)(), const Arguments&)’ is deprecated [-Wdeprecated-declarations]
   29 |     myExtension.add("say_hello", say_hello);
      |                                           ^
In file included from /usr/include/phpcpp.h:70,
                 from main.cpp:1:
/usr/include/phpcpp/namespace.h:118:34: note: declared here
  118 |     PHPCPP_DEPRECATED Namespace &add(const char *name, const native_callback_0 &function, const Arguments &arguments = {});
      |                                  ^~~

**Comment by gnat42** [comment] 2021-01-01 17:28
I vaguely remember hitting an issue like this and if I recall the issue is compilation with too old of gcc... but its a vague memory so I can't be 100% sure.

**Comment by nazmulpcc** [comment] 2021-04-24 01:27
This one goes away if you include `stdexcept` in `/usr/include/phpcpp/throwable.h` file.

**Comment by sallyx** [comment] 2022-04-16 14:28
Fixed by #440

**Comment by carlos-granados** [comment] 2023-01-25 18:39
There is a maintained fork where a PR to fix this issue has been merged, you can find it here: https://github.com/fast-debug/PHP-CPP

**Comment by robocoder** [comment] 2023-11-21 21:22
Fixed in PHP-CPP 2.4.0 (c2b36b9843b4b98f67342f6c0a956d1217bcb948)

**Closed** 2023-11-22 08:19 UTC
